language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
notifications:
  email: true
before_install:
  - sudo apt-get install libhdf5-serial-dev netcdf-bin libnetcdf-dev
  - pip install numpy cython python-dateutil
install:
  - pip install .
script:
  - python test/run_all.py
