language: python

dist: trusty
sudo: required

env:
  global:
    - DEPENDS="numpy cython"
    - NO_NET=1

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"

matrix:
  include:
    # Absolute minimum dependencies.
    - python: 2.6
      env:
        - DEPENDS="numpy==1.7.0 cython==0.19 ordereddict==1.1"
      before_install: # override default and install default netcdf (4.1.3)
        - sudo apt-get update -q
        - sudo apt-get install libhdf5-serial-dev
        - sudo apt-get install netcdf-bin
        - sudo apt-get install libnetcdf-dev
        - sudo apt-get install libnetcdfc7
        - pip install $DEPENDS
    # Test without Cython installed.
    - python: 2.6
      env:
        - DEPENDS="numpy ordereddict"

notifications:
  email: false

before_install:
# commenting out next line gets newer netcdf (4.3.3.1)
#  - sudo add-apt-repository ppa:heiko-klein/netcdf -y
  - sudo add-apt-repository ppa:nschloe/netcdf-backports -y
  - sudo add-apt-repository ppa:nschloe/hdf5-backports -y
  - sudo apt-get update -q
  - sudo apt-get install libhdf5-serial-dev
  - sudo apt-get install netcdf-bin
  - sudo apt-get install libnetcdf-dev
  - sudo apt-get install libnetcdfc7
  - pip install $DEPENDS

install:
  - python setup.py build
  - python setup.py install

script:
  - cd test
  - python run_all.py
