language: python

sudo: false

addons:
  apt:
    packages:
      - libhdf5-serial-dev
      - netcdf-bin
      - libnetcdf-dev

env:
  global:
    - DEPENDS="numpy cython setuptools==18.0.1"
    - NO_NET=1
    - MPI=0

python:
  - "2.7"
  - "3.5"
  - "3.6"

matrix:
  allow_failures:
    - python: "3.7-dev"
    - env: MPI=1
  include:
    # Absolute minimum dependencies.
    - python: 2.7
      env:
        - DEPENDS="numpy==1.9.0 cython==0.21 ordereddict==1.1 setuptools==18.0"
    # test MPI
    - python: 2.7
      env: 
        - MPI=1

notifications:
  email: false

before_install:
  - pip install $DEPENDS

install:
  - python setup.py build
  - python setup.py install

script:
  - |
    if [ $MPI -eq 1 ] ; then
       cd examples
       pwd
       ls -l mpi_example.py
       mpirun -np 4 python mpi_example.py
       cd ..
    fi
  - cd test
  - python run_all.py
