language: python
env:
    global:
        - DEPENDS="numpy cython"
python:
  - "2.7"
  - "3.3"
  - "3.4"
matrix:
  include:
    # Absolute minimum dependencies
    - python: 2.7
      env:
        - DEPENDS="numpy==1.6.0 cython==0.19"
    # test without Cython installed
    - python: 2.7
      env:
        - DEPENDS="numpy"
notifications:
  email: false
before_install:
  - sudo apt-get install libhdf5-serial-dev netcdf-bin libnetcdf-dev
  - pip install $DEPENDS
install:
  - python setup.py build
  - python setup.py install
script:
  - cd test
  - python run_all.py
